"""
BNBTASwapMA Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import BNBTASwapMAStrategy
except ImportError:
    from strategy import BNBTASwapMAStrategy

__all__ = [
    "BNBTASwapMAStrategy",
]
